services:
    controller.home:
        class: AppBundle\Controller\HomeController

    controller.create_new_todo_list:
        class: AppBundle\Controller\CreateNewTodoListController
        arguments:
            - '@repository.todo_list'
            - '@factory.todo_list'
            - '@router'

    controller.todo_list_detail:
        class: AppBundle\Controller\TodoListDetailController
        arguments:
            - '@repository.todo_list'

    # API
    controller.api.todo_list_detail:
        class: AppBundle\Controller\ApiTodoListDetailController
        arguments:
            - '@repository.todo_list'
            - '@response.factory.todo_list'

    controller.api.todo_list_item_check:
        class: AppBundle\Controller\TodoListItemCheckedController
        arguments:
            - '@repository.todo_list'
            - '@response.factory.todo_list_item'

    controller.api.todo_list_item_remove:
        class: AppBundle\Controller\TodoListItemRemoveController
        arguments:
            - '@repository.todo_list'
            - '@response.factory.todo_list_item'

    controller.api.todo_list_item_create:
        class: AppBundle\Controller\TodoListItemCreateController
        arguments:
            - '@repository.todo_list'
            - '@response.factory.todo_list_item'
            - '@form.factory'
