services:
    repository.todo_list:
        class: AppBundle\Repository\TodoListRepository
        factory: [ '@doctrine', getRepository ]
        arguments:
            - 'AppBundle\Entity\TodoList'
