home:
    path: /
    defaults: { _controller: controller.home:homeAction }

create_new_todo_list:
    path: /create-new-todo-list
    defaults: { _controller: controller.create_new_todo_list:createAction }

todo_list_detail:
    path: /todo-list/{id}/{token}
    defaults: { _controller: controller.todo_list_detail:detailAction }
    requirements:
        id: \d+

# Api
api_todo_list_detail:
    path: /api/todo-list/{id}/{token}.json
    defaults: { _controller: controller.api.todo_list_detail:detailAction, _format: json }
    requirements:
        id: \d+
    options:
        expose: true

api_todo_list_item_check:
    path: /api/todo-list/{todoListId}/{todoListToken}/items/{id}/check.json
    defaults: { _controller: controller.api.todo_list_item_check:checkAction, _format: json }
    methods: PUT
    requirements:
        todoListId: \d+
        id: \d+
    options:
        expose: true

api_todo_list_item_uncheck:
    path: /api/todo-list/{todoListId}/{todoListToken}/items/{id}/uncheck.json
    defaults: { _controller: controller.api.todo_list_item_check:uncheckAction, _format: json }
    methods: PUT
    requirements:
        todoListId: \d+
        id: \d+
    options:
        expose: true

api_todo_list_item_remove:
    path: /api/todo-list/{todoListId}/{todoListToken}/items/{id}/remove.json
    defaults: { _controller: controller.api.todo_list_item_remove:removeAction, _format: json }
    methods: DELETE
    requirements:
        todoListId: \d+
        id: \d+
    options:
        expose: true

api_todo_list_item_create:
    path: /api/todo-list/{todoListId}/{todoListToken}/items/create.json
    defaults: { _controller: controller.api.todo_list_item_create:createAction, _format: json }
    methods: POST
    requirements:
        todoListId: \d+
    options:
        expose: true

api_todo_list_item_edit:
    path: /api/todo-list/{todoListId}/{todoListToken}/items/{id}/edit.json
    defaults: { _controller: controller.api.todo_list_item_edit:editAction, _format: json }
    methods: PUT
    requirements:
        todoListId: \d+
        id: \d+
    options:
        expose: true
