home:
    path: /
    defaults: { _controller: controller.home:homeAction }

create_new_todo_list:
    path: /create-new-todo-list
    defaults: { _controller: controller.create_new_todo_list:createAction }

todo_list_detail:
    path: /todo-list/{id}/{token}
    defaults: { _controller: controller.todo_list_detail:detailAction }
    requirements:
        id: \d+

# Api
api_todo_list_detail:
    path: /api/todo-list/{id}/{token}.json
    defaults: { _controller: controller.api.todo_list_detail:detailAction, _format: json }
    requirements:
        id: \d+
    options:
        expose: true
