AppBundle\Entity\TodoListItem:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        description:
            type: text
            length: 10000
            nullable: true
        checked:
            type: boolean
        deadline:
            type: date
            nullable: true
    manyToOne:
        todoList:
            targetEntity: AppBundle\Entity\TodoList
            inversedBy: items
            joinColumn:
                name: todo_list_id
                referencedColumnName: id
                onDelete: cascade
                nullable: false
