AppBundle\Entity\TodoListItem:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        checked:
            type: boolean
    manyToOne:
        todoList:
            targetEntity: AppBundle\Entity\TodoList
            inversedBy: items
            joinColumn:
                name: todo_list_id
                referencedColumnName: id
                onDelete: cascade
