AppBundle\Entity\TodoList:
    type: entity
    repositoryClass: AppBundle\Repository\TodoListRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        token:
            type: string
            unique: true
        createdAt:
            type: datetime
    oneToMany:
        items:
            targetEntity: AppBundle\Entity\TodoListItem
            mappedBy: todoList
            cascade: ['all']
